
management:
  endpoints:
    web.exposure.include: health, info, prometheus
  endpoint:
    health:
      group:
        liveness.include: "livenessState"
        readiness.include: "readinessState"
      show-components: never
  health.livenessstate.enabled: true
  health.readinessstate.enabled: true
  info.git.enabled: true

server:
  shutdown: graceful

spring:
  application:
    name: Crud Image
  datasource:
    url: jdbc:h2:file:./data/testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true
    path: /h2-console
  security.user:
    name: user         # Default user name.
    password: password # Password for the default user name.
    roles: USER        # Granted roles for the default user
